// Top 100 US airports
export const airports = [
  { id: 'ATL', name: 'Hartsfield–Jackson Atlanta International Airport' },
  { id: 'LAX', name: 'Los Angeles International Airport' },
  { id: 'ORD', name: "O'Hare International Airport" },
  { id: 'DFW', name: 'Dallas/Fort Worth International Airport' },
  { id: 'DEN', name: 'Denver International Airport' },
  { id: 'JFK', name: 'John F. Kennedy International Airport' },
  { id: 'SFO', name: 'San Francisco International Airport' },
  { id: 'SEA', name: 'Seattle–Tacoma International Airport' },
  { id: 'LAS', name: 'Harry Reid International Airport' },
  { id: 'MIA', name: 'Miami International Airport' },
  { id: 'CLT', name: 'Charlotte Douglas International Airport' },
  { id: 'PHX', name: 'Phoenix Sky Harbor International Airport' },
  { id: 'EWR', name: 'Newark Liberty International Airport' },
  { id: 'IAH', name: 'George Bush Intercontinental Airport' },
  { id: 'MCO', name: 'Orlando International Airport' },
  { id: 'MSP', name: 'Minneapolis-Saint Paul International Airport' },
  { id: 'DTW', name: 'Detroit Metropolitan Airport' },
  { id: 'PHL', name: 'Philadelphia International Airport' },
  { id: 'LGA', name: 'LaGuardia Airport' },
  { id: 'BWI', name: 'Baltimore/Washington International Airport' },
  { id: 'SLC', name: 'Salt Lake City International Airport' },
  { id: 'DCA', name: 'Ronald Reagan Washington National Airport' },
  { id: 'MDW', name: 'Chicago Midway International Airport' },
  { id: 'HNL', name: 'Daniel K. Inouye International Airport' },
  { id: 'BOS', name: 'Logan International Airport' },
  { id: 'FLL', name: 'Fort Lauderdale-Hollywood International Airport' },
  { id: 'IAD', name: 'Washington Dulles International Airport' },
  { id: 'SAN', name: 'San Diego International Airport' },
  { id: 'TPA', name: 'Tampa International Airport' },
  { id: 'PDX', name: 'Portland International Airport' },
  { id: 'STL', name: 'St. Louis Lambert International Airport' },
  { id: 'HOU', name: 'William P. Hobby Airport' },
  { id: 'OAK', name: 'Oakland International Airport' },
  { id: 'AUS', name: 'Austin-Bergstrom International Airport' },
  { id: 'MCI', name: 'Kansas City International Airport' },
  { id: 'RDU', name: 'Raleigh-Durham International Airport' },
  { id: 'CLE', name: 'Cleveland Hopkins International Airport' },
  { id: 'SJC', name: 'Norman Y. Mineta San Jose International Airport' },
  { id: 'SMF', name: 'Sacramento International Airport' },
  { id: 'IND', name: 'Indianapolis International Airport' },
  { id: 'CMH', name: 'John Glenn Columbus International Airport' },
  { id: 'BNA', name: 'Nashville International Airport' },
  { id: 'PIT', name: 'Pittsburgh International Airport' },
  { id: 'MSY', name: 'Louis Armstrong New Orleans International Airport' },
  { id: 'BUR', name: 'Hollywood Burbank Airport' },
  { id: 'DAL', name: 'Dallas Love Field' },
  { id: 'JAX', name: 'Jacksonville International Airport' },
  { id: 'ONT', name: 'Ontario International Airport' },
  { id: 'MEM', name: 'Memphis International Airport' },
  { id: 'RSW', name: 'Southwest Florida International Airport' },
  { id: 'SNA', name: 'John Wayne Airport' },
  { id: 'CVG', name: 'Cincinnati/Northern Kentucky International Airport' },
  { id: 'MKE', name: 'Milwaukee Mitchell International Airport' },
  { id: 'BDL', name: 'Bradley International Airport' },
  { id: 'BUF', name: 'Buffalo Niagara International Airport' },
  { id: 'ABQ', name: 'Albuquerque International Sunport' },
  { id: 'OGG', name: 'Kahului Airport' },
  { id: 'TUL', name: 'Tulsa International Airport' },
  { id: 'OKC', name: 'Will Rogers World Airport' },
  { id: 'OMA', name: 'Eppley Airfield' },
  { id: 'RNO', name: 'Reno-Tahoe International Airport' },
  { id: 'CHS', name: 'Charleston International Airport' },
  { id: 'GEG', name: 'Spokane International Airport' },
  { id: 'PBI', name: 'Palm Beach International Airport' },
  { id: 'BOI', name: 'Boise Airport' },
  { id: 'TUS', name: 'Tucson International Airport' },
  { id: 'ELP', name: 'El Paso International Airport' },
  { id: 'ANC', name: 'Ted Stevens Anchorage International Airport' },
  { id: 'LGB', name: 'Long Beach Airport' },
  { id: 'FAT', name: 'Fresno Yosemite International Airport' },
  { id: 'ALB', name: 'Albany International Airport' },
  { id: 'SYR', name: 'Syracuse Hancock International Airport' },
  { id: 'ROC', name: 'Greater Rochester International Airport' },
  { id: 'GRR', name: 'Gerald R. Ford International Airport' },
  { id: 'DAY', name: 'Dayton International Airport' },
  { id: 'DSM', name: 'Des Moines International Airport' },
  { id: 'ICT', name: 'Wichita Dwight D. Eisenhower National Airport' },
  { id: 'SAV', name: 'Savannah/Hilton Head International Airport' },
  { id: 'GSP', name: 'Greenville-Spartanburg International Airport' },
  { id: 'RIC', name: 'Richmond International Airport' },
  { id: 'PVD', name: 'T. F. Green Airport' },
  { id: 'BHM', name: 'Birmingham-Shuttlesworth International Airport' },
  { id: 'MOB', name: 'Mobile Regional Airport' },
  { id: 'TYS', name: 'McGhee Tyson Airport' },
  { id: 'CAE', name: 'Columbia Metropolitan Airport' },
  { id: 'GSO', name: 'Piedmont Triad International Airport' },
  { id: 'AVL', name: 'Asheville Regional Airport' },
  { id: 'LEX', name: 'Blue Grass Airport' },
  { id: 'SDF', name: 'Louisville Muhammad Ali International Airport' },
  { id: 'EVV', name: 'Evansville Regional Airport' },
  { id: 'FWA', name: 'Fort Wayne International Airport' },
  { id: 'GRB', name: 'Green Bay Austin Straubel International Airport' },
  { id: 'MSN', name: 'Dane County Regional Airport' },
  { id: 'CID', name: 'The Eastern Iowa Airport' },
  { id: 'LNK', name: 'Lincoln Airport' },
  { id: 'XNA', name: 'Northwest Arkansas National Airport' },
  { id: 'FAY', name: 'Fayetteville Regional Airport' },
  { id: 'ILM', name: 'Wilmington International Airport' },
  { id: 'MYR', name: 'Myrtle Beach International Airport' },
  { id: 'CHO', name: 'Charlottesville-Albemarle Airport' },
  { id: 'ROA', name: 'Roanoke-Blacksburg Regional Airport' },
  { id: 'LYH', name: 'Lynchburg Regional Airport' },
];
